### ISSUE TITLE
无法获取到lora的插件列表

### ISSUE THREAD

**Issue by zh2009053012** [FernRender/FernSDGraph#4]
无法获取到lora的插件列表
看了一下源码，是通过sdapi/v1/lora来获取的，但是在sd的源码api.py里并未找到此api，是不是作者自己修改了sd-webui的源码新增的接口？

**Comment by DumoeDss** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/10194
api是使用on_app_started callbac加在extensions-builtin/Lora/lora.py里的

**Comment by zh2009053012** [comment]
不懂，作者大大能否详细说一下？本人刚接触sd，而且python也不熟，属于盲人摸象阶段
