### ISSUE TITLE
示例Room报错

### ISSUE THREAD

**Issue by zh2009053012** [FernRender/FernSDGraph#5]
报错提示：
WebException: The remote server returned an error: (422) Unprocessable Entity.
应该是ControlNet节点导致的，但是具体原因不知道

**Comment by DumoeDss** [comment]
请先检查api是否能够正常使用。

**Comment by zh2009053012** [comment]
需要在config.json中将disable_all_extensions配置项由extra修改为none，否则自定义插件无法加载（使用ControlNet插件会报错）
